
uint64 timestamp		# time since system start (microseconds)

# record Euler angle
float32 record_roll
float32 record_pitch
float32 record_yaw
# record other information
float32 record_input_error_y
float32 record_input_error_z
float32 record_control_y
float32 record_control_z 
float32 record_damp_y
float32 record_damp_z 
float32 frame_z_error
float32 frame_x_error
float32 frame_y_error
float32 frame_vz_error
float32 frame_vy_error
float32 frame_vx_error